services:   # services we want to include
  # 1. service
  pgdatabase:
    image: postgres:13
    # environment variables
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    # volumes to mount
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    # port mapping
    ports:
      - "5432:5432"
    networks:
      - pg-network

  # 2. service
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    networks:
      - pg-network



# network
networks:
  pg-network:
    driver: bridge
